"""Add borrowing_capacity to CustomerModel

Revision ID: 1ad938744a49
Revises: bb873abb1ce9
Create Date: 2026-02-25 15:55:37.791002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ad938744a49'
down_revision = 'bb873abb1ce9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('borrowing_capacity', sa.Numeric(precision=18, scale=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('borrowing_capacity')

    # ### end Alembic commands ###
