"""Initial schema designed mathematically for COP

Revision ID: bb873abb1ce9
Revises: 
Create Date: 2026-02-25 05:41:14.677255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb873abb1ce9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chart_of_accounts',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('nature', sa.Enum('DEBIT', 'CREDIT', name='account_nature_enum'), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.Enum('CC', 'CE', 'NIT', 'PASSPORT', name='document_type_enum'), nullable=False),
    sa.Column('document_number', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('credit_score', sa.Integer(), nullable=True),
    sa.Column('risk_classification', sa.Enum('A', 'B', 'C', 'D', 'E', name='portfolio_risk_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('credit_score BETWEEN 0 AND 1000', name='chk_customer_credit_score'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_type', 'document_number', name='uq_customer_document')
    )
    op.create_table('journal_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entry_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('operation_reference', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journal_entry_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('journal_entry_id', sa.UUID(), nullable=False),
    sa.Column('account_code', sa.String(length=20), nullable=False),
    sa.Column('debit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('credit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.CheckConstraint('credit >= 0', name='chk_journal_credit'),
    sa.CheckConstraint('debit >= 0', name='chk_journal_debit'),
    sa.ForeignKeyConstraint(['account_code'], ['chart_of_accounts.code'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('requested_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('approved_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('interest_rate', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('interest_rate_type', sa.Enum('EAR', 'NMV', name='interest_rate_type_enum'), nullable=False),
    sa.Column('term_months', sa.Integer(), nullable=False),
    sa.Column('payment_modality', sa.Enum('FIXED_INSTALLMENT', 'CONSTANT_PRINCIPAL', name='payment_modality_enum'), nullable=False),
    sa.Column('status', sa.Enum('SUBMITTED', 'APPROVED', 'DISBURSED', 'CURRENT', 'IN_ARREARS', 'RESTRUCTURED', 'WRITTEN_OFF', 'PAID', name='loan_status_enum'), nullable=False),
    sa.Column('application_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('disbursement_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('approved_amount > 0', name='chk_loans_approved_amount'),
    sa.CheckConstraint('interest_rate >= 0', name='chk_loans_interest_rate'),
    sa.CheckConstraint('requested_amount > 0', name='chk_loans_requested_amount'),
    sa.CheckConstraint('term_months > 0', name='chk_loans_term_months'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loans_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_loans_status'), ['status'], unique=False)

    op.create_table('amortization_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('loan_id', sa.UUID(), nullable=False),
    sa.Column('installment_number', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('principal_payment', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('interest_payment', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('life_insurance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('other_charges', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_installment_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('principal_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.CheckConstraint('installment_number > 0', name='chk_amortization_installment_number'),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('loan_id', 'installment_number', name='uq_loan_installment')
    )
    with op.batch_alter_table('amortization_schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_amortization_schedules_due_date'), ['due_date'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('loan_id', sa.UUID(), nullable=False),
    sa.Column('payment_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('payment_reference', sa.String(length=100), nullable=False),
    sa.Column('payment_method', sa.Enum('PSE', 'BANK_DEPOSIT', 'AUTO_DEBIT', 'BANK_AGENT', name='payment_method_enum'), nullable=False),
    sa.CheckConstraint('paid_amount > 0', name='chk_payments_paid_amount'),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_reference')
    )
    op.create_table('payment_allocations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('amortization_schedule_id', sa.UUID(), nullable=True),
    sa.Column('legal_fees_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('insurance_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('default_interest_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('ordinary_interest_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('principal_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['amortization_schedule_id'], ['amortization_schedules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_allocations')
    op.drop_table('payments')
    with op.batch_alter_table('amortization_schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_amortization_schedules_due_date'))

    op.drop_table('amortization_schedules')
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loans_status'))
        batch_op.drop_index(batch_op.f('ix_loans_customer_id'))

    op.drop_table('loans')
    op.drop_table('journal_entry_lines')
    op.drop_table('journal_entries')
    op.drop_table('customers')
    op.drop_table('chart_of_accounts')
    # ### end Alembic commands ###
